version: "2.2"
services:
  iris:
    image: irisopcua
    build:
      context: iris
      dockerfile: Dockerfile
    ports:
      - 52773:52773
      - 1972:1972
    env_file: .env

  opcua:
    init: true
    image: opcua-server
#    entrypoint: ["python", "/app/server.py", "--nodes", "10", "--sleep", "0.1"]
    build:
      context: opcua
      dockerfile: Dockerfile
    ports:
      - 4840:4840