version: "2.2"
services:
  iris:
    init: true
    image: irisopcua
    build:
      context: iris
      dockerfile: Dockerfile
    ports:
      - 52773:52773
      - 1972:1972
    volumes:
      - ./iris.key:/usr/irissys/mgr/iris.key:ro

  py:
    init: true
    image: opcua-server
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - 4840:4840